### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by XimikRU** [Garik-/empty-file-server#1]
Hi, i have following errors after npm start:

```
$ yarn
yarn install v1.7.0
warning package.json: No license field
info No lockfile found.
warning easy-file-server@0.0.1: No license field
[1/4] Resolving packages...
warning unzip > fstream > graceful-fs > natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
warning mocha > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning nodemon > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning nodemon > chokidar > fsevents@1.2.12: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning nodemon > chokidar > braces > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning nodemon > chokidar > braces > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
[2/4] Fetching packages...
info fsevents@1.2.12: The platform "win32" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-config-prettier-standard@2.0.0" has incorrect peer dependency "eslint-config-prettier@^2.9.0".
warning " > eslint-config-prettier-standard@2.0.0" has incorrect peer dependency "eslint-config-standard@^11.0.0".
warning " > eslint-loader@2.1.0" has unmet peer dependency "webpack@>=2.0.0 <5.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 181.61s.
```

```
$ npm start

> easy-file-server@0.0.1 start C:\Users\Илья\Desktop\SOCIAL_FS
> node src/server.js

fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer
    at Object.fs.openSync (fs.js:646:18)
    at fs.writeFileSync (fs.js:1299:33)
    at FileSync.read (C:\Users\Илья\Desktop\SOCIAL_FS\node_modules\lowdb\adapters\FileSync.js:46:9)
    at LodashWrapper.db.read (C:\Users\Илья\Desktop\SOCIAL_FS\node_modules\lowdb\lib\main.js:32:21)
    at module.exports (C:\Users\Илья\Desktop\SOCIAL_FS\node_modules\lowdb\lib\main.js:51:13)
    at Object.<anonymous> (C:\Users\Илья\Desktop\SOCIAL_FS\src\db.js:5:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! easy-file-server@0.0.1 start: `node src/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the easy-file-server@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Илья\AppData\Roaming\npm-cache\_logs\2020-05-04T11_26_13_765Z-debug.log
```

win 8.1 x64
npm 5.6.0
yarn 1.7.0
node 8.10 / 8.12 / 10.0

Can you help pls?

**Comment by Garik-** [comment]
`info fsevents@1.2.12: The platform "win32" is incompatible with this module.`
Hi, i don't have windows. Try to use Docker build.
